### ISSUE TITLE
Get Audit quote/price

### ISSUE THREAD

**Issue by xrchz** [rocketlend/admin#1]
This can contain a single comment without being an issue? OK - so now it's an issue and can have a conversation :)

**Comment by xrchz** [comment]
From Charles VI in Discord, auditor possibilities:
- Chainlight 
- Sigma prime x
- Consensys 
- Deadub 
- Audit contest w hats finance/code4rena/sherlock
- Openzepplin *
- Trail of bits x
- Abdk x
> Asterisks were remarked on favorably and Xes were not
> Seemed like folks thought an audit competition would yield the best bang/buck

**Comment by xrchz** [comment]
I have indicative pricing from Sigma Prime and from Sherlock. (Won't share here publicly since they like to keep these things confidential..)

**Comment by digiantnz** [comment]
@xrchz  Do you want me to hit up Openzepplin?

**Comment by xrchz** [comment]
Sure, go for it.

**Comment by digiantnz** [comment]
Hi @xrchz  Still waiting to hear back from OpenZepplin but they did suggest this link

https://www.openzeppelin.com/request

Not sure if you want to fill it all in @ this stage or just wait for a response back from the email for an indicative quote

**Comment by xrchz** [comment]
I'm fine either way. Lemme know what you wouldn't be able to fill yourself in that form...

**Comment by digiantnz** [comment]
OPenZepplin have requested filling in their form. 

https://www.openzeppelin.com/request 

Confirming @xrchz is good with supplying the info

**Comment by xrchz** [comment]
Since we are not a company, I wonder if that form or this auditor is even appropriate... we would have to put a bunch of placeholders into the form saying we are not a company. I'm not that keen on filling it out myself.

**Comment by digiantnz** [comment]
Let me reply to the guy with the repo (and our we're not quite a company yet excuse) and see what happens

**Comment by digiantnz** [comment]
Still no response from OpenZepplin @xrchz  have a look at this https://code4rena.com/how-it-works/project

**Comment by digiantnz** [comment]
Request submitted to open4rena for review

**Comment by digiantnz** [comment]
HI @xrchz  can you confirm the following response from OZ?, Cheers

Hi Matt - yes, we can prep an initial quote. 
To do so, could you please confirm the specific files to be included in-scope?

thanks

**Comment by xrchz** [comment]
rocketlend.vy is the only file in scope.

**Comment by digiantnz** [comment]
Replied to OZ with file for audit

**Comment by digiantnz** [comment]
Reached out to  code4rena on telegram (@trebienxyz) for timeframe/next steps

**Comment by digiantnz** [comment]
@xrchz  - What is the audit budget? Cheers

**Comment by xrchz** [comment]
See the information from the GMC https://dao.rocketpool.net/t/round-14-jun-7-jul-7-grants-bounties-retrospective-awards-results/3161

**Comment by digiantnz** [comment]
Meeting with aren4code


You are scheduled
A calendar invitation has been sent to your email address.
30 Minute Meeting
trebien | C4
9:00pm - 9:30pm, Friday, August 2, 2024
Auckland Time
Web conferencing details to follow.

**Comment by digiantnz** [comment]
Hi @xrchz  Heard back from OZ "our team estimates that an audit will require 2 auditors for pricing-wise, our standard rate is 24k per auditor week. **$92K**" Responded saying we have 30K but I would shop around and get back to him

Meeting withe code4rena friday 21:00 NZT  not _exactly_ sure what the agenda is but I asked to discuss where the process is at and possible time frames

Hit me up if you want to ride along and I'll forward the invite

**Comment by digiantnz** [comment]
Meeting with Sherlock

Tuesday, 6 August 2024
08:30 – 09:00 (GMT+12)

**Comment by digiantnz** [comment]
code4rena quote received

**Comment by digiantnz** [comment]
All quotes recieved
