### ISSUE TITLE
Complete Smart Contract  Alpha

### ISSUE THREAD

**Issue by digiantnz** [rocketlend/admin#18]
Complete specs of each smart contract, including the RocketPool contracts/integrations, their purpose, and their interactions

**Comment by digiantnz** [comment]
Hi @xrchz  just keeping this in admin as a high level progress marker. This is pretty much the critical path to the testing and the audit

Any idea of when you might have it ready?

**Comment by digiantnz** [comment]
HI @xrchz  I'll out out the end date to the end of the weekend to give some of rocket lend community time to review

**Comment by digiantnz** [comment]
Can we close this? (There is another task for post testnet updates)

**Comment by xrchz** [comment]
I guess so!
