### ISSUE TITLE
Setup Doc repository

### ISSUE THREAD

**Issue by digiantnz** [rocketlend/admin#3]
Somewhere to store reports/findings confidential project docs

**Comment by digiantnz** [comment]
@xrchz  any preference for non-public/tech doc storage? (p.s. not a fan of google ;))

**Comment by xrchz** [comment]
We could use a private repo on GitHub, or I'm happy to self host a git repo if you prefer. Eg we probably wanna grab a rocketlend domain anyway.

**Comment by digiantnz** [comment]
Can it store .doc .xls docs? (I'll put another job in for the URL :) )

**Comment by xrchz** [comment]
Of course you can put anything in git... I'm not sure what you want these docs for though - those aren't formats that are easy for me to read

**Comment by digiantnz** [comment]
You're such a dev ;) they'll be all the docs we have to supply to others. Just need secure storage :D

**Comment by xrchz** [comment]
Yeah just make a private git repo I think on GitHub

**Comment by digiantnz** [comment]
HI @xrchz well how about you make one (and stick the sigma prime and sherlock quotes in it ;) Cheers!

**Comment by xrchz** [comment]
This is done: see the https://github.com/rocketlend/confidential repository

**Comment by digiantnz** [comment]
Nice.
