### ISSUE TITLE
Find time tracking software

### ISSUE THREAD

**Issue by xrchz** [rocketlend/admin#4]
Find a time tracking tool to record actual hours on the project

**Comment by xrchz** [comment]
Can this be done retroactively from commits and messages? e.g. using rocket scrape for discord?

**Comment by digiantnz** [comment]
I'll add that into the tool considerations

I'm familiar with this https://toggl.com/track/pricing/ so I'll throw this in

**Comment by digiantnz** [comment]
Not seeing (free) tools that can do timekeeping retroactively currently (Timely/Harvest are mentioned but only 30day trial)

**Comment by digiantnz** [comment]
https://everhour.com/pricing

**Comment by digiantnz** [comment]
https://clockify.me/pricing#compare

**Comment by digiantnz** [comment]
Installed and testing everhour

**Comment by digiantnz** [comment]
Looks like everhour is also only a trial (set to expire next week) Will review clockify

**Comment by digiantnz** [comment]
Clockify seems to be working fine.
