### ISSUE TITLE
Define fee structure

### ISSUE THREAD

**Issue by digiantnz** [rocketlend/admin#5]
**Define Rocketlend's fee structure**

basically there are a lot of options and I don't have that much of an opinion on what to do except to meet the requirements:
it has to pay for our time spent so far, and future dev if needed (e.g. the frontend)
it has to pay for the audits (under the assumption audits are required for anyone to actually use this)
it has to avoid any serious legal risks
it should be compatible with any other sources of funding for the above costs we might incur (but in which case it doesn't have to cover all the costs itself)

_What is the plan for Rocket Lend to take a protocol fee or fund via a token?_

What is the fee on - borrowed RPL, interest, something else? 

How is the fee amount determined - is there an admin multisig that can change it? is it immutable or with immutable guardrails? 

How can it be responsive to the market? do we do a token in addition to or instead of a fee? - could we follow the approach peteris suggested? 

What are the legal risks of any fees or tokens?

**Comment by digiantnz** [comment]
Hi @xrchz Are you able to start writing some of this down into a doc? Do we need to solicit assistance on this? 

Where is the comment you mention around tokens from peteris?

**Comment by xrchz** [comment]
> Where is the comment you mention around tokens from peteris?

Where I got to is here
https://discord.com/channels/405159462932971535/1238452361719054336/1254336451538190368
The messages from peteris and discussion of things about it (regarding the TRU token) are in the messages above that.

**Comment by digiantnz** [comment]
HI @xrchz  has this been completed/defined now?

**Comment by xrchz** [comment]
I think so. The answer is simple: no protocol fee :)
